// demo/components/stat.tsx
import type { JSX } from "solid-js";

type StatProps = {
  class?: string;
  title: string;
  description?: string;
  value?: JSX.Element;
  centered?: boolean;
};

function Stat(props: StatProps) {
  return (
    <div class={`stats ${props.class}`}>
      <div
        class="stat"
        classList={{
          "place-items-center": props.centered,
        }}
      >
        <div class="stat-title">{props.title}</div>
        <div class="stat-value font-light">{props.value}</div>
        <div class="stat-desc">{props.description}</div>
      </div>
    </div>
  );
}

export { Stat };

// packages/app/src/components/stat.svelte
<script lang="ts">
  interface Props {
    title: string;
    value: string | number;
    unit?: string;
    desc: string;
  }

  let { title, value, unit, desc }: Props = $props();
</script>

<div class="stats">
  <div class="stat border-neutral rounded-box border">
    <div class="stat-title">{title}</div>
    <div class="stat-value">
      {value}
      {#if unit}
        <span class="text-base-content/75 text-xs font-light">{unit}</span>
      {/if}
    </div>
    <div class="stat-desc">{desc}</div>
  </div>
</div>
