// packages/app/src/components/drawer.svelte
<script lang="ts">
  import type { Snippet } from "svelte";

  interface Props {
    open?: boolean;
    content?: Snippet;
    sidebar?: Snippet;
  }

  let { open: checked = $bindable(false), content, sidebar }: Props = $props();
  let id = $props.id();
</script>

<div class="drawer lg:drawer-open h-dvh">
  <input bind:checked {id} type="checkbox" class="drawer-toggle" />
  <div class="drawer-content">
    {#if content}
      {@render content()}
    {/if}
  </div>
  <div class="drawer-side">
    <label aria-label="close sidebar" class="drawer-overlay" for={id}></label>
    {#if sidebar}
      {@render sidebar()}
    {/if}
  </div>
</div>

// packages/web/src/components/drawer.tsx
import { createUniqueId, type JSX } from "solid-js";

type DrawerProps = {
  children?: JSX.Element;
  sidebar?: JSX.Element;
};

type DrawerToggleProps = {
  children?: JSX.Element;
  class?: string;
};

const id = createUniqueId();

function Drawer(props: DrawerProps) {
  return (
    <div class="drawer lg:drawer-open">
      <input id={id} type="checkbox" class="drawer-toggle" />
      <section class="drawer-content">{props.children}</section>
      <section class="drawer-side" style={{ "scrollbar-gutter": "stable" }}>
        <label
          for={id}
          aria-label="close sidebar"
          class="drawer-overlay"
        ></label>
        {props.sidebar}
      </section>
    </div>
  );
}

function DrawerToggle(props: DrawerToggleProps) {
  return (
    <label for={id} class={`drawer-button lg:hidden ${props.class}`}>
      {props.children}
    </label>
  );
}

export { Drawer, DrawerToggle };
